### ISSUE TITLE
Using already obtained posterior samples

### ISSUE THREAD

**Issue by jonasmac16** [theogf/ThermodynamicIntegration.jl#19]
Hi,
This package looks super interesting. I was wondering if it possible to use already obtained posterior samples from a Turing model to calculate the evidence rather than rerunning the model?

Best Jonas

**Comment by theogf** [comment]
Hi @jonasmac16, I don't think it would make a lot of sense to use obtained posterior samples as this would just be a minor part of the algorithm...
In TI, you sample from the power posterior for different temperatures (power on the likelihood) and samples for the posterior would only correspond to samples from the final temperature at T=1.

**Comment by theogf** [comment]
Closing this as stale.
